version: "3.9"

# Services configuration for the MyBrand Job Application Platform
# This file defines all services that make up the application platform
services:
  # Redis service for caching and real-time messaging
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  # Skill Gap Analyzer Microservice
  # Analyzes skill gaps between resumes and job descriptions
  skill_gap_analyzer:
    build:
      context: ./microservices/skill_gap_analyzer
    ports:
      - "8105:8105"
    environment:
      - PORT=8105
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8105/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Resume Builder Microservice
  # Generates professional resumes from structured data
  resume_builder:
    build:
      context: ./microservices/resume_builder
    ports:
      - "8106:8106"
    environment:
      - PORT=8106
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8106/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Resume Enhancer Microservice
  # Improves existing resumes with AI-powered suggestions
  resume_enhancer:
    build:
      context: ./microservices/resume_enhancer
    ports:
      - "8107:8107"
    environment:
      - PORT=8107
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8107/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Interview Prep Coach Microservice
  # Generates personalized interview questions and preparation tips
  interview_coach:
    build:
      context: ./microservices/interview_coach
    ports:
      - "8108:8108"
    environment:
      - PORT=8108
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Job Application Auto-Fill Microservice
  # Extracts data from resumes and auto-fills job application forms
  application_filler:
    build:
      context: ./microservices/application_filler
    ports:
      - "8109:8109"
    environment:
      - PORT=8109
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8109/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Semantic Job Matcher Microservice
  # Finds jobs that match user skills and career goals using semantic analysis
  semantic_matcher:
    build:
      context: ./microservices/semantic_matcher
    ports:
      - "8110:8110"
    environment:
      - PORT=8110
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8110/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Personalized Job Recommender Microservice
  # Recommends jobs based on user preferences and career history
  job_recommender:
    build:
      context: ./microservices/job_recommender
    ports:
      - "8111:8111"
    environment:
      - PORT=8111
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8111/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Mock Interviewer Microservice
  # Conducts practice interviews with AI-powered feedback
  mock_interviewer:
    build:
      context: ./microservices/mock_interviewer
    ports:
      - "8114:8114"
    environment:
      - PORT=8114
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8114/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Diversity & Inclusion Insights Microservice
  # Provides insights on diversity and inclusion in job opportunities
  diversity_insights:
    build:
      context: ./microservices/diversity_insights
    ports:
      - "8115:8115"
    environment:
      - PORT=8115
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8115/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Document Summarizer Microservice
  # Summarizes job descriptions and other documents
  document_summarizer:
    build:
      context: ./microservices/document_summarizer
    ports:
      - "8116:8116"
    environment:
      - PORT=8116
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8116/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Voice Agent Microservice
  # Provides voice-based interaction for hands-free job searching
  voice_agent:
    build:
      context: ./microservices/voice_agent
    ports:
      - "8117:8117"
    environment:
      - PORT=8117
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8117/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Multi-Language Support Microservice
  # Provides translation and localization services
  multi_language:
    build:
      context: ./microservices/multi_language
    ports:
      - "8118:8118"
    environment:
      - PORT=8118
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8118/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Course Recommendation Engine Microservice
  # Recommends courses for skill development
  course_recommender:
    build:
      context: ./microservices/course_recommender
    ports:
      - "8119:8119"
    environment:
      - PORT=8119
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8119/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Placeholder worker service (will be wired later)
  worker:
    build:
      context: ./backend/workers
    command: ["node", "dist/index.js"]
    environment:
      - REDIS_URL=redis://redis:6379
      - API_URL=http://backend:8000
    depends_on:
      redis:
        condition: service_healthy
    profiles: ["workers"]

  # Backend (FastAPI) placeholder (wired later)
  backend:
    build:
      context: ./backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE=${SUPABASE_SERVICE_ROLE}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - APP_URL=${APP_URL:-http://localhost:3000}
      # Comment out dependencies for now to test independently
      # - SKILL_GAP_SERVICE_URL=http://skill_gap_analyzer:8105
      # - RESUME_BUILDER_SERVICE_URL=http://resume_builder:8106
      # - RESUME_ENHANCER_SERVICE_URL=http://resume_enhancer:8107
      # - INTERVIEW_COACH_SERVICE_URL=http://interview_coach:8108
      # - APPLICATION_FILLER_SERVICE_URL=http://application_filler:8109
      # - SEMANTIC_MATCHER_SERVICE_URL=http://semantic_matcher:8110
      # - JOB_RECOMMENDER_SERVICE_URL=http://job_recommender:8111
      # - MOCK_INTERVIEWER_SERVICE_URL=http://mock_interviewer:8114
      # - DIVERSITY_INSIGHTS_SERVICE_URL=http://diversity_insights:8115
      # - DOCUMENT_SUMMARIZER_SERVICE_URL=http://document_summarizer:8116
      # - VOICE_AGENT_SERVICE_URL=http://voice_agent:8117
      # - MULTI_LANGUAGE_SERVICE_URL=http://multi_language:8118
      # - COURSE_RECOMMENDER_SERVICE_URL=http://course_recommender:8119
    # Comment out dependencies for now to test independently
    # depends_on:
    #   redis:
    #     condition: service_healthy
    #   skill_gap_analyzer:
    #     condition: service_healthy
    #   resume_builder:
    #     condition: service_healthy
    #   resume_enhancer:
    #     condition: service_healthy
    #   interview_coach:
    #     condition: service_healthy
    #   application_filler:
    #     condition: service_healthy
    #   semantic_matcher:
    #     condition: service_healthy
    #   job_recommender:
    #     condition: service_healthy
    #   mock_interviewer:
    #     condition: service_healthy
    #   diversity_insights:
    #     condition: service_healthy
    #   document_summarizer:
    #     condition: service_healthy
    #   voice_agent:
    #     condition: service_healthy
    #   multi_language:
    #     condition: service_healthy
    #   course_recommender:
    #     condition: service_healthy
    profiles: ["backend"]

  # Frontend (Vite/React)
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    profiles: ["frontend"]
    # Remove dependency for now to avoid circular dependency issues
    # depends_on:
    #   backend:
    #     condition: service_started

# Network configuration
# Defines the default network for all services
networks:
  default:
    name: mybrand-net